// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Experiment: typeof import('./components/Experiment.vue')['default']
    Grid: typeof import('./components/Grid.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HeaderHome: typeof import('./components/HeaderHome.vue')['default']
    Social: typeof import('./components/Social.vue')['default']
    Typing: typeof import('./components/Typing.vue')['default']
  }
}

export { }
