// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Copy: typeof import('./components/Copy.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HeaderHome: typeof import('./components/HeaderHome.vue')['default']
    README: typeof import('./components/README.md')['default']
    Typing: typeof import('./components/Typing.vue')['default']
  }
}

export { }
